// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Summary of a configured model provider.
 */
export type ProviderInfo = { 
/**
 * Key in the providers map (e.g. `"openai"`, `"ollama"`).
 */
id: string, 
/**
 * Friendly display name.
 */
name: string, 
/**
 * Base URL for the provider's API.
 */
baseUrl: string | null, 
/**
 * Wire protocol: `"responses"` or `"chat"`.
 */
wireApi: string, 
/**
 * Environment variable that stores the API key.
 */
envKey: string | null, 
/**
 * Whether this provider requires OpenAI authentication.
 */
requiresOpenaiAuth: boolean, };
