// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderInfo } from "./ProviderInfo";

/**
 * Response for `provider/list`.
 */
export type ProviderListResponse = { data: Array<ProviderInfo>, };
