// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf";
import type { CollaborationMode } from "../CollaborationMode";
import type { MultiAgentMode } from "../MultiAgentMode";
import type { Personality } from "../Personality";
import type { ReasoningEffort } from "../ReasoningEffort";
import type { ReasoningSummary } from "../ReasoningSummary";
import type { JsonValue } from "../serde_json/JsonValue";
import type { AdditionalContextEntry } from "./AdditionalContextEntry";
import type { ApprovalsReviewer } from "./ApprovalsReviewer";
import type { AskForApproval } from "./AskForApproval";
import type { CyberAccessProgram } from "./CyberAccessProgram";
import type { SandboxPolicy } from "./SandboxPolicy";
import type { TurnEnvironmentParams } from "./TurnEnvironmentParams";
import type { TurnToolOutput } from "./TurnToolOutput";
import type { UserInput } from "./UserInput";

export type TurnStartParams = {threadId: string, clientUserMessageId?: string | null, input: Array<UserInput>, /**
 * Optional source classification for the caller that starts this turn.
 * Ignored when this request steers an already-active turn.
 */
turnTrigger?: string | null, toolOutput?: TurnToolOutput | null, /**
 * Optional turn-scoped Responses API client metadata.
 */
responsesapiClientMetadata?: Record<string, string> | null, /**
 * Optional client-provided context fragments keyed by an opaque source identifier.
 */
additionalContext?: Record<string, AdditionalContextEntry> | null, /**
 * Optional turn-scoped environments.
 *
 * Omitted uses the thread sticky environments. Empty disables
 * environment access for this turn. Non-empty selects the first
 * environment as the current turn environment for this turn.
 */
environments?: Array<TurnEnvironmentParams> | null, /**
 * Override the working directory for this turn and subsequent turns.
 */
cwd?: string | null, /**
 * Replace the thread's runtime workspace roots for this turn and
 * subsequent turns. Paths must be absolute.
 */
runtimeWorkspaceRoots?: Array<AbsolutePathBuf> | null, /**
 * Override the approval policy for this turn and subsequent turns.
 */
approvalPolicy?: AskForApproval | null, /**
 * Override where approval requests are routed for review on this turn and
 * subsequent turns.
 */
approvalsReviewer?: ApprovalsReviewer | null, /**
 * Override the sandbox policy for this turn and subsequent turns.
 */
sandboxPolicy?: SandboxPolicy | null, /**
 * Select a named permissions profile for this turn and subsequent turns.
 * Cannot be combined with `sandboxPolicy`. Use bounded `modifications`
 * for supported turn adjustments instead of replacing the full
 * permissions profile.
 */
permissions?: string | null, /**
 * Override the model for this turn and subsequent turns.
 */
model?: string | null, /**
 * Override the service tier for this turn and subsequent turns.
 */
serviceTier?: string | null | null, /**
 * Override the service tier only when this request starts a new turn.
 * Use "default" for standard speed. Omitted or null inherits the thread's tier.
 * Does not change the thread's tier or a turn being steered.
 */
serviceTierForTurn?: string | null, /**
 * Override the reasoning effort for this turn and subsequent turns.
 */
effort?: ReasoningEffort | null, /**
 * Override the reasoning summary for this turn and subsequent turns.
 */
summary?: ReasoningSummary | null, /**
 * Override the personality for this turn and subsequent turns.
 */
personality?: Personality | null, /**
 * Optional JSON Schema used to constrain the final assistant message for
 * this turn.
 */
outputSchema?: JsonValue | null, /**
 * EXPERIMENTAL - Set a pre-set collaboration mode.
 * Takes precedence over model, reasoning_effort, and developer instructions if set.
 *
 * For `collaboration_mode.settings.developer_instructions`, `null` means
 * "use the built-in instructions for the selected mode".
 */
collaborationMode?: CollaborationMode | null, /**
 * @deprecated Ignored. Use `effort: "ultra"` for proactive multi-agent behavior.
 */
multiAgentMode?: MultiAgentMode | null, /**
 * EXPERIMENTAL - Request a workspace-authorized cyber program for this
 * turn. Omission preserves automatic behavior. This does not grant access.
 */
cyberAccessProgram?: CyberAccessProgram | null};
