// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type PromptKnowledgeEntry = { id: string | null, keys: Array<string>, secondaryKeys: Array<string>, content: string, enabled: boolean, insertionOrder: bigint | null, position: string | null, metadata: JsonValue | null, };
