// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PromptKnowledgeEntry } from "./PromptKnowledgeEntry";
import type { JsonValue } from "./serde_json/JsonValue";

export type PromptKnowledgeSource = { name: string | null, kind: string | null, description: string | null, entries: Array<PromptKnowledgeEntry>, metadata: JsonValue | null, };
