// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PromptGreetingKind } from "./PromptGreetingKind";

export type PromptGreeting = { kind: PromptGreetingKind, text: string, };
