// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PromptDepthPrompt } from "./PromptDepthPrompt";
import type { PromptExample } from "./PromptExample";
import type { PromptGreeting } from "./PromptGreeting";
import type { PromptIdentity } from "./PromptIdentity";
import type { PromptKnowledgeSource } from "./PromptKnowledgeSource";
import type { PromptSourceOrigin } from "./PromptSourceOrigin";
import type { JsonValue } from "./serde_json/JsonValue";

export type PromptSource = { id: string | null, name: string | null, origin: PromptSourceOrigin | null, identity: PromptIdentity | null, scenario: string | null, systemOverlay: string | null, postHistoryInstructions: string | null, creatorNotes: string | null, greetings: Array<PromptGreeting>, examples: Array<PromptExample>, depthPrompt: PromptDepthPrompt | null, variables: { [key in string]?: string }, knowledge: Array<PromptKnowledgeSource>, rawExtensions: JsonValue | null, };
