// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type PromptKnowledgeEntry = { content: string, enabled: boolean, id: string | null, insertionOrder: bigint | null, keys: Array<string>, metadata: JsonValue | null, position: string | null, secondaryKeys: Array<string>, };
