// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PromptInjectionRole } from "./PromptInjectionRole";

export type PromptExampleMessage = { role: PromptInjectionRole, content: string, };
